name: Backend Image CI

on:
  push:
    branches: 
      - be
  pull_request:
    branches: 
      - be

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD     
    - name: Switch to be branch
      run: |
        git fetch --all
        git switch be
        cd be
    - name: Build the Docker image
      working-directory: be
      run: docker build -t lets_kirin-api .
    - name: taging
      env:
        DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      run: docker tag lets_kirin-api:latest ${DOCKER_USERNAME}/lets_kirin-api:latest
    - name: Push to Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      run: docker push ${DOCKER_USERNAME}/lets_kirin-api:latest
